#================================================
## Gene Co-expression Network — Leiden Clustering
## Fixed seed: 12345
##================================================

rm(list = ls())

SEED <- 12345
set.seed(SEED)  # ★ 반드시 가장 먼저 고정

library(dplyr)
library(readr)
library(igraph)
library(tidygraph)
library(tibble)

## ─────────────────────────────────────────────
## 0. Settings
## ─────────────────────────────────────────────
FILE_CORR <- "../Filtered_correlation_pairs.rds"
# ===========================================

CORR_CUTOFF <- 0.7   # |r| 하한
P_CUTOFF    <- 0.05  # p-value 상한
RES_VALUES  <- seq(1.0, 3.0, by = 0.25)  # Leiden resolution sweep 범위
SELECT_BY <- "ARI_NMI_distance_to_1"

#setwd(DIR_WORK)
today <- format(Sys.Date(), "%Y-%m-%d")

## 출력 폴더 생성
make_dir <- function(path) { dir.create(path, recursive = TRUE, showWarnings = FALSE); path }

out_leiden  <- make_dir(paste0("./Leiden_Results/",   today, "/"))
out_compare <- make_dir(paste0("./Compare/",          today, "/"))
out_node    <- make_dir(paste0("./Table_NodeInfo/",    today, "/"))
out_cluster <- make_dir(paste0("./Cluster_Stats/",     today, "/"))
log_file    <- paste0(out_leiden, "Leiden_run.log")

log_msg <- function(...) {
  msg <- paste0(...)
  cat(msg, "\n")
  cat(msg, "\n", file = log_file, append = TRUE)
}

cat("", file = log_file, append = FALSE)  # 로그 초기화
log_msg("=== Script start: ", Sys.time(), " ===")
log_msg("seed fixed: ", SEED)

## ─────────────────────────────────────────────
## 1. Load & filter correlation pairs
## ─────────────────────────────────────────────
DataCorr <- readRDS(FILE_CORR) %>%
  setNames(c("Gene_1", "Gene_2", "Correlation", "Pvalue")) %>%
  filter(abs(Correlation) >= CORR_CUTOFF, Pvalue < P_CUTOFF)

log_msg("Loaded pairs: ", nrow(DataCorr))

## ─────────────────────────────────────────────
## 2. Remove singleton edges (degree == 1 양쪽 모두)
## ─────────────────────────────────────────────
deg_raw <- table(c(DataCorr$Gene_1, DataCorr$Gene_2))
singletons <- names(deg_raw[deg_raw == 1])

DataCorr <- DataCorr %>%
  filter(!(Gene_1 %in% singletons & Gene_2 %in% singletons))

log_msg("After singleton removal: ", nrow(DataCorr), " pairs")

## ─────────────────────────────────────────────
## 3. Build graph
## ─────────────────────────────────────────────
g <- graph_from_data_frame(DataCorr[, c("Gene_1", "Gene_2")], directed = FALSE) %>%
  simplify(remove.multiple = TRUE, remove.loops = TRUE) %>%
  delete_vertices(which(degree(.) == 0))

if (vcount(g) == 0 | ecount(g) == 0) stop("Network가 비어 있습니다. 필터 조건을 확인하세요.")
log_msg("Graph — nodes: ", vcount(g), " | edges: ", ecount(g))

## ─────────────────────────────────────────────
## 4. Precompute centralities
## ─────────────────────────────────────────────
deg_vec <- degree(g)
btw_vec <- betweenness(g, normalized = TRUE)
cls_vec <- closeness(g, normalized = TRUE)

## ─────────────────────────────────────────────
## 5. Load Leiden/Louvain comparison result
## ─────────────────────────────────────────────
compare_file <- paste0(out_compare, "Leiden_vs_Louvain_compare.csv")
if (!file.exists(compare_file)) {
  stop("Comparison file not found: ", compare_file,
       "\nRun Leiden_Louvain_test.R first in the same working directory.")
}

compare_df <- read_csv(compare_file, show_col_types = FALSE)
if ("ari" %in% names(compare_df)) compare_df <- compare_df %>% rename(ARI = ari)
if ("nmi" %in% names(compare_df)) compare_df <- compare_df %>% rename(NMI = nmi)
if (!"score" %in% names(compare_df)) {
  compare_df <- compare_df %>%
    mutate(score = (ARI + NMI) / 2)
}
if (!"distance_to_1" %in% names(compare_df)) {
  compare_df <- compare_df %>%
    mutate(distance_to_1 = sqrt((1 - ARI)^2 + (1 - NMI)^2))
}

chosen_row <- compare_df %>%
  filter(!is.na(distance_to_1)) %>%
  arrange(distance_to_1, desc(score), desc(ARI), desc(NMI), resolution) %>%
  slice(1)

if (nrow(chosen_row) != 1) stop("No valid resolution found from ARI/NMI comparison.")

chosen_res <- chosen_row$resolution
write_csv(chosen_row, paste0(out_compare, "Chosen_resolution_by_ARI_NMI.csv"))

log_msg("Chosen resolution closest to ARI/NMI = 1: ", chosen_res,
        " | Leiden clusters: ", chosen_row$leiden_clusters,
        " | ARI: ", chosen_row$ARI,
        " | NMI: ", chosen_row$NMI,
        " | distance_to_1: ", chosen_row$distance_to_1,
        " | score: ", chosen_row$score)

## ─────────────────────────────────────────────
## 6. Load Leiden communities generated by Leiden_Louvain_test.R
## ─────────────────────────────────────────────
leiden_results <- list()
leiden_summary <- list()

for (resv in RES_VALUES) {
  res_key <- as.character(resv)
  comm_file <- paste0(out_leiden, "Leiden_res", resv, "_comm.rds")
  if (!file.exists(comm_file)) {
    stop("Leiden community file not found: ", comm_file,
         "\nRun Leiden_Louvain_test.R first with matching RES_VALUES.")
  }

  log_msg("Loading Leiden resolution = ", resv)
  cl <- readRDS(comm_file)
  memb <- membership(cl)

  if (!setequal(names(memb), V(g)$name)) {
    stop("Membership genes do not match the graph genes for resolution ", resv)
  }

  ## membership 저장
  memb_df <- tibble(Gene = names(memb), cluster = as.integer(memb))
  write_csv(memb_df, paste0(out_node, "Leiden_res", resv, "_membership.csv"))

  ## 클러스터 크기 통계 저장
  write_csv(
    tibble(cluster = names(sizes(cl)), size = as.integer(sizes(cl))) %>% arrange(desc(size)),
    paste0(out_cluster, "Leiden_res", resv, "_cluster_stats.csv")
  )

  ## tbl_graph 저장
  g_tg <- as_tbl_graph(g) %>%
    activate(nodes) %>%
    mutate(
      cluster     = memb[name],
      Degree      = deg_vec[name],
      Betweenness = btw_vec[name],
      Closeness   = cls_vec[name]
    )
  saveRDS(g_tg, paste0(out_leiden, "g_tg_Leiden_res", resv, ".rds"))

  leiden_results[[res_key]] <- list(comm = cl)
  leiden_summary[[res_key]] <- tibble(
    resolution = resv,
    n_clusters = length(cl),
    top5       = paste(head(sort(sizes(cl), decreasing = TRUE), 5), collapse = ", "),
    selected   = resv == chosen_res
  )
}

summary_df <- bind_rows(leiden_summary)
write_csv(summary_df, paste0(out_leiden, "Leiden_summary_modularity.csv"))
log_msg("Leiden community loading done.")

chosen_comm <- leiden_results[[as.character(chosen_res)]]$comm

## ─────────────────────────────────────────────
## 7. Node annotation (Hub / Connector / Bridge / Key)
## ─────────────────────────────────────────────
find_bridge_genes <- function(graph, memb_vec) {
  el <- as_edgelist(graph) %>% as.data.frame(stringsAsFactors = FALSE)
  colnames(el) <- c("from", "to")
  inter <- el %>% filter(memb_vec[from] != memb_vec[to])
  unique(c(inter$from, inter$to))
}

bridge_genes <- find_bridge_genes(g, membership(chosen_comm))

thr_deg <- quantile(deg_vec, 0.95)
thr_btw <- quantile(btw_vec, 0.95)
thr_cls <- quantile(cls_vec, 0.95)

node_tbl <- tibble(
  name        = V(g)$name,
  cluster     = as.integer(membership(chosen_comm)[V(g)$name]),
  degree      = deg_vec[V(g)$name],
  betweenness = btw_vec[V(g)$name],
  closeness   = cls_vec[V(g)$name]
) %>%
  mutate(
    HubGene       = degree      >= thr_deg,
    ConnectorGene = betweenness >= thr_btw | closeness >= thr_cls,
    BridgeGene    = name %in% bridge_genes,
    KeyGene       = (HubGene | ConnectorGene) & BridgeGene
  )

write_csv(node_tbl,
          paste0(out_node, "Node_annotation_Leiden_res", chosen_res, ".csv"))

## ─────────────────────────────────────────────
## 8. Cluster stats (chosen resolution)
## ─────────────────────────────────────────────
cluster_stats <- sort(unique(node_tbl$cluster)) %>%
  lapply(function(cid) {
    subg <- induced_subgraph(g, V(g)[membership(chosen_comm) == cid])
    tibble(cluster = cid, node_count = vcount(subg), edge_count = ecount(subg))
  }) %>%
  bind_rows() %>%
  arrange(desc(node_count))

write_csv(cluster_stats,
          paste0(out_cluster, "Cluster_stats_Leiden_res", chosen_res, ".csv"))

## ─────────────────────────────────────────────
## 9. Save final tbl_graph (chosen resolution + all annotations)
## ─────────────────────────────────────────────
g_tg_final <- as_tbl_graph(g) %>%
  activate(nodes) %>%
  left_join(node_tbl, by = "name")

saveRDS(g_tg_final,
        paste0(out_leiden, "g_tg_Leiden_FINAL_res", chosen_res, ".rds"))

## ─────────────────────────────────────────────
## 10. Wrap-up
## ─────────────────────────────────────────────
log_msg("=== Script end: ", Sys.time(), " ===")
log_msg("Outputs saved to: ", out_leiden, " | ", out_node, " | ", out_cluster)
cat("Done.\n")
